name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'
      
    - name: Restore dependencies and build
      run: |
        dotnet restore
        dotnet build --configuration Release

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Push to GitLab
      run: |
        git remote add gitlab https://gitlab.com/dotnetcore2181108/JwtImpl.git
        git push gitlab main
